# Generated by Django 3.1.7 on 2022-05-13 22:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='vision',
            field=tinymce.models.HTMLField(),
        ),
    ]
