# Generated by Django 3.1.7 on 2022-05-14 10:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220514_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='partners',
            name='logo',
            field=models.ImageField(upload_to='Images/Partner_Logo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
    ]
