# Generated by Django 3.1.7 on 2022-05-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220514_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(default='', upload_to='Images/Team'),
            preserve_default=False,
        ),
    ]
