# Generated by Django 3.1.7 on 2022-05-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactusmessages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='mission',
            name='years',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, upload_to='Images/Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.subcategory'),
        ),
    ]
